### ISSUE TITLE
layout bug in fiori fundamental 1.4.1

### ISSUE THREAD

**Issue by DamianLion** [SAP/fundamental-vue#123]
rel: https://github.com/SAP/fundamental/issues/1199

#### Is this a bug, enhancement, or feature request?
bug

#### Which versions of Vue.JS and Fundamental Vue are affected? (If this is a feature request, use current version.)

vue-fundamental 0.0.9-beta
fiori-fundamental 1.4.1

#### If this is a bug, please provide steps for reproducing it.

https://codepen.io/DeltaM/pen/VgZpvY

#### Is there anything else we should know?

I provided a fix which works for us

```
.fd-app__main {
  -webkit-box-flex: 1;
  -ms-flex: 1;
  flex: 1;
}
```

**Comment by ChristianKienle** [comment]
This is fixed in 1.4.9.
