### ISSUE TITLE
Edge detection for popover-style elements

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental-vue#134]
popovers (and other popup style components. should edge-detect and flip where there is no space.

[popperjs](https://popper.js.org/) / [popperjs github](https://github.com/FezVrasta/popper.js)  provides this functionality, and has libraries to react, angular and vue

https://www.npmjs.com/package/react-popper
https://www.npmjs.com/package/ngx-popper
https://www.npmjs.com/package/vue-popperjs

SAP Concur has previously had good success with popper.js, and implemented within our pre-fundamentals components library.

![image](https://user-images.githubusercontent.com/5056972/52000765-bc90f900-2472-11e9-9193-559fb166dc2b.png)

also see 
https://github.com/SAP/fundamental-ngx/issues/410 and 
https://github.com/SAP/fundamental-react/issues/313

**Comment by ChristianKienle** [comment]
This has been implemented in https://github.com/SAP/fundamental-vue/tree/feature/popper.

PR should be created soon.

**Comment by ChristianKienle** [comment]
@suwarnoong I am assigning this to you if you don't mind since you have done most of the work already. :D

**Comment by ChristianKienle** [comment]
Will be fixed by #291. Merge incoming. Closing already,
