### ISSUE TITLE
update README to use the IE11 css instead of non-IE11

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-vue#164]
#### Is this a bug, enhancement, or feature request?
documentation
#### Briefly describe your proposal.
fundamental-vue needs to support IE11. `README.md` advises the user to include css file fiori-fundamentals, which doesn't support IE11
#### Which versions of Vue.JS and Fundamental Vue are affected? (If this is a feature request, use current version.)
latest

#### Is there anything else we should know?

**Comment by ChristianKienle** [comment]
Fixed by #173
