### ISSUE TITLE
Implement Date Picker Component

### ISSUE THREAD

**Issue by CodesOfRa** [SAP/fundamental-vue#2]
Fundamental-UI [Date Picker](https://sap.github.io/fundamental/components/date-picker.html) Component
Visuals:
 [Date Picker](https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/screen/5b030418b943834d22447a03) 
[Single Date Picker](https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/screen/5b0d62a6501a39c37583407d)
[Range Date Picker](https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/screen/5b030418e215dc29221d2a76)

**Comment by tudorels** [comment]
When do you think Date Picker Component will be ready for use?
Thank you?

**Comment by ChristianKienle** [comment]
@tudorels If you go to the [calendar documentation](https://sap.github.io/fundamental-vue/#/example/calendar) you can see an example where we combine a popover with a calendar. This is – of course – only a poor mans date picker. @CodesOfRa rightfully mentioned to me that the date-input component is missing in this "poor man's" date picker. So here is my question: Have you seen our poor man's date picker and is this good enough (for now) or do you need it in combination with some kind of input field. The component is currently in progress. Depending on your needs we could speed it up.

**Comment by tudorels** [comment]
I'm planning to migrate the interface of an application developed with openui5 to fundamental-vue and we plan to start in one month, so we necessarily need it in combination with input field(a true datepicker).
I hope to hear good news soon from you! Thank you!

**Comment by ChristianKienle** [comment]
@tudorels the date picker pull request is now open #405. It will take a few more days to work out the rough edges. Do you mind talking more about your plans? Would love to hear from you via e-email (see my github profile).

**Comment by ChristianKienle** [comment]
@tudorels we now have a date picker component. yay. Enjoy.
