### ISSUE TITLE
Docs broken on mobile

### ISSUE THREAD

**Issue by mobot11** [SAP/fundamental-vue#260]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Docs are broken on mobile, see screenshot.

<img width="396" alt="mobile_docs" src="https://user-images.githubusercontent.com/9958488/54727238-e8a42e80-4b33-11e9-92ba-9136f735615a.png">

#### Which versions of Vue.JS and Fundamental Vue are affected? (If this is a feature request, use current version.)
Current
#### If this is a bug, please provide steps for reproducing it.
1) Navigate to https://sap.github.io/fundamental-vue/#/start
2) resize screen to mobile width

#### Is there anything else we should know?

**Comment by ChristianKienle** [comment]
@mobot11 thanks! 

I have made it responsive: https://streamable.com/59cw3

PR incoming.

**Comment by ChristianKienle** [comment]
Fixed. Will be released with 0.2.
