### ISSUE TITLE
Bug: Calendar component next month click 

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-vue#324]
#### Is this a bug, enhancement, or feature request?
bug

Related to https://github.com/SAP/fundamental-ngx/issues/855

Fundamental-react was having some problems with the Calendar component this morning due to it being the 31st, which shows up in the next month on our calendar. I was looking at ngx and vue to see how you handled it and found that the next button skips June. I'm betting this is due to the same problem as in fundamental-react - having previous months days show up in the calendar.

#### If this is a bug, please provide steps for reproducing it.

![2019-05-31 09 15 24](https://user-images.githubusercontent.com/29607818/58719540-ca08b200-8384-11e9-927d-0027a33ccbc3.gif)

#### Is there anything else we should know?

**Comment by ChristianKienle** [comment]
will be fixed by #405
