### ISSUE TITLE
Bug: Search field overlap on Shell bar when scrolling down/up

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-vue#347]
#### Briefly describe your proposal.
The search field in the Search input component overlap on the Shell bar when it remains open and the user scrolls up or down.

#### If this is a bug, please provide steps for reproducing it.
1. Navigate to Search input. 
2. Scroll down. 
3. Observe the search field on the Shell bar. 

See screenshot. 
<img width="722" alt="Screen Shot 2019-06-13 at 11 15 45 AM" src="https://user-images.githubusercontent.com/25252963/59445014-dd783c00-8dcc-11e9-86dd-1826dc889b6a.png">

**Comment by ChristianKienle** [comment]
@SaiShan thanks for reporting this issue. I have noticed that as well (a while back) and concluded that this is not an issue with fundamental vue but with fundamental itself. This is why I created an issue ( https://github.com/SAP/fundamental/issues/1441 ) and hoped to see it fixed. :) @droshev I have noticed that issue 1141 was not migrated to the new repo. Was that done intentionally?

**Comment by ChristianKienle** [comment]
I have now also created an issue in the new repo. I will close the issue here.

@SaiShan If you want to follow along - here is the new issue I have created:

https://github.com/SAP/fundamental-styles/issues/94
