### ISSUE TITLE
SearchInput Interaction

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental-vue#35]
PR #32 added the SearchInput component. It supports basic interactions like clicking on the search button. However some interactions are missing. For example:

- Support for Arrow Keys
- Support for ESC
- …

However it is not yet clear to us what kind of interactions are required. At the time of writing neither the React nor the Angular colleagues seem to have implemented the SearchInput component. Thus we have to first collect all interactions that we want to have and the implement them.

- [ ] Talk to colleagues (UX/NGX/Fundamental/React) about the SearchInput interactions.
- [ ] Write them down somewhere (here?) and then...
- [ ] Implement the interactions to make the SearchInput component fully functional.

**Comment by khmmrl** [comment]
Hi @ChristianKienle,
any updates on this? 

From my point of view, the most important features would be:
- Arrow keys to scroll through the proposal list
- Type-Ahead search (-> TAB to take over proposal)

Best regards, Kay

**Comment by ChristianKienle** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/153225/57186976-65267d00-6ee8-11e9-8148-43a7da474bfc.gif)

@khmmrl 

this is the current state of things which I am (still) working on.

- Arrow-keys work
- dismiss on Esc
- confirm on enter

it still has rough edges but I am getting there. Does this look like it could work for you?

**Comment by khmmrl** [comment]
Looks good. For detailed feedback I would have to use it first :)

**Comment by ChristianKienle** [comment]
> Looks good. For detailed feedback I would have to use it first :)

Sure think. You can play with it once I open the PR. It will then get automatically deployed in a test environment. I will ping you once the PR is open.
