### ISSUE TITLE
[Date-picker][Calender] : On Month or Year selection , the popover disappears. 

### ISSUE THREAD

**Issue by AdityaKumarSharma** [SAP/fundamental-vue#657]
#### Is this a bug, enhancement, or feature request?
This is a BUG

#### Briefly describe your proposal.
Open Date-picker component . Click to open it and select the month or year , you will observe that 
Popover disappears. 

#### If this is a bug, please provide steps for reproducing it.
Attaching the screen shot

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-vue/#/examples/date-picker

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/33654140/72130833-a4269f80-33a0-11ea-8579-003d5048ffc8.png)

**Comment by ChristianKienle** [comment]
fixed by #662
