### ISSUE TITLE
is this project still maintained?

### ISSUE THREAD

**Issue by vneecious** [SAP/fundamental-vue#908]
I've noticed that the last commit was from 2 years ago and the last release is from 2019. A lot of issues are unanswered, and there are more than 40 PRs awaiting review. Besides that, the new [Fundamental website](https://sap.github.io/fundamental/#fl-libraries) only mentions the Fundamental Styles and Angular. Are there any plans for this library, or should we consider it abandoned?

**Comment by droshev** [comment]
@vneecious Unfortunately the project is not any maintenance or support. I guess our next step is to deprecate it.
